name: Continuous Integration

on:
  workflow_dispatch:
  push:
  #    branches-ignore:
  #        - master
  #pull_request:
  #    branches:
  #        - master

jobs:
  php-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.2, 8.3, 8.4]

    steps:
      - uses: shivammathur/setup-php@v2
        name: Use PHP ${{ matrix.php-version }}
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests
        run: composer test
